GET http://localhost:8080/healthy

###
POST http://localhost:8080/categories
Content-Type: application/json

{
    "name":"books"
}


###
GET  http://localhost:8080/categories

###
GET  http://localhost:8080/categories/35d204a9-20ae-42f5-9807-7a26bd328e05
